---
title: Making a Website with Blogdown, R, and HUGO Academic Theme
author: Arnie
date: '2020-12-21'
slug: making-a-website-with-blogdown-r-and-hugo-academic-theme
categories:
  - guide
tags:
  - R
  - blogdown
  - HUGO
subtitle: ''
summary: ''
authors: []
lastmod: '2020-12-21T19:36:17-08:00'
featured: no
image:
  caption: 'https://xkcd.com/181/'
  focal_point: ''
  preview_only: no
projects: []
---

Since you are reading this, I assume you want to join us on the glorious webtubeways of the blagoblag!  And now that I am an expert having built not five, not a hundred, but one --- __one!__ --- website, I feel qualified to show you how to do it too!


...so actually I just wanted to share my experience of getting this thing up and running, in the hopes of saving you some pain and time.  I use R, Rmarkdown, and Github daily, but I came into this with roughly, oh, about exactly zero experience with HTML, HUGO, or the `blogdown` package (see paragraph above).  


I use R, Rmarkdown, and Github daily, but I started making this website with roughly about exactly zero experience with HTML, HUGO, or the `blogdown` package.  This post is not the best guide for everyone; there are much better guides out there.  But if you're coming to this from a situation similar to mine,  saving you some pain and time, and to offload some notes for myself.






I found HUGO and/or the Academic theme to be pretty finicky, but that may have been because I was following the wrong guide.  The guide I recommend is [this presentation by Alison Hill, given at rstudio::conf 2019](https://arm.rbind.io/slides/blogdown.html).  






# Table of Contents:

```{r echo=FALSE}
render_toc <- function(
  filename, 
  toc_header_name = "Table of Contents",
  base_level = NULL,
  toc_depth = 3
) {
  # credit Garrick Aden-Buie
  # https://www.garrickadenbuie.com/blog/add-a-generated-table-of-contents-anywhere-in-rmarkdown/
  x <- readLines(filename, warn = FALSE)
  x <- paste(x, collapse = "\n")
  x <- paste0("\n", x, "\n")
  for (i in 5:3) {
    regex_code_fence <- paste0("\n[`]{", i, "}.+?[`]{", i, "}\n")
    x <- gsub(regex_code_fence, "", x)
  }
  x <- strsplit(x, "\n")[[1]]
  x <- x[grepl("^#+", x)]
  if (!is.null(toc_header_name)) 
    x <- x[!grepl(paste0("^#+ ", toc_header_name), x)]
  if (is.null(base_level))
    base_level <- min(sapply(gsub("(#+).+", "\\1", x), nchar))
  start_at_base_level <- FALSE
  x <- sapply(x, function(h) {
    level <- nchar(gsub("(#+).+", "\\1", h)) - base_level
    if (level < 0) {
      stop("Cannot have negative header levels. Problematic header \"", h, '" ',
           "was considered level ", level, ". Please adjust `base_level`.")
    }
    if (level > toc_depth - 1) return("")
    if (!start_at_base_level && level == 0) start_at_base_level <<- TRUE
    if (!start_at_base_level) return("")
    if (grepl("\\{#.+\\}(\\s+)?$", h)) {
      # has special header slug
      header_text <- gsub("#+ (.+)\\s+?\\{.+$", "\\1", h)
      header_slug <- gsub(".+\\{\\s?#([-_.a-zA-Z]+).+", "\\1", h)
    } else {
      header_text <- gsub("#+\\s+?", "", h)
      header_text <- gsub("\\s+?\\{.+\\}\\s*$", "", header_text) # strip { .tabset ... }
      header_text <- gsub("^[^[:alpha:]]*\\s*", "", header_text) # remove up to first alpha char
      header_slug <- paste(strsplit(header_text, " ")[[1]], collapse="-")
      header_slug <- tolower(header_slug)
    }
    paste0(strrep(" ", level * 4), "- [", header_text, "](#", header_slug, ")")
  })
  x <- x[x != ""]
  knitr::asis_output(paste(x, collapse = "\n"))
}

render_toc(filename="index.en.Rmd")
```




# Resources

- Alison Hill's 2019 rstudio::conf slides: https://arm.rbind.io/slides/blogdown.html
- 








